### ISSUE TITLE
Dateien werden nicht gefunden

### ISSUE THREAD

**Issue by tdoerig** [kdietrich/node-devolo#6]
Hallo

Das Plugin lässt sich bei mir nicht installieren.

<img width="820" alt="Bildschirmfoto 2020-05-06 um 09 57 44" src="https://user-images.githubusercontent.com/23149050/81150379-1474b480-8f80-11ea-845f-6f6615036657.png">

Grüsse
Tobias

**Comment by nicoh88** [comment]
`apt install git`

**Comment by tdoerig** [comment]
Super, hat geklappt. Danke!
